apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: iap-config
  namespace: istio-system
spec:
  healthCheck:
    requestPath: /healthz/ready
    port: 32477
    type: HTTP
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: kfserving-api-secret